#!/usr/bin/env ruby
ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
ENV['RACK_ENV'] = 'script'

require 'rubygems'
require 'bundler'
require 'ruby-debug'
Bundler.setup

require File.join(ROOT, 'lib', 'disharmony')

#stupid-simple approximation of a irb-like console using ruby-debug
debugger
1+1
