#!/usr/bin/env ruby

ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
ENV['RACK_ENV'] = 'test'

require 'rubygems'
require 'ruby-debug'
Dir[File.join(ROOT, "vendor/*/lib")].each { |path| $:.unshift path } 

require 'bundler'
Bundler.setup

require File.join(ROOT, 'lib', 'disharmony')

Disharmony::Logger = Logger.new(STDOUT)
debugger
1+1
