#!/usr/bin/env ruby

ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
ENV['RACK_ENV'] = 'production'

require 'rubygems'
require 'ruby-debug'
Dir[File.join(ROOT, "vendor/*/lib")].each { |path| $:.unshift path } 

require File.join(ROOT, 'lib', 'disharmony')

Disharmony::Logger = Logger.new(STDOUT)

Disharmony.new.download_latest
