#!/usr/bin/env ruby

ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
ENV['RACK_ENV'] = 'script'

require 'rubygems'
require 'bundler'
Bundler.setup

require File.join(ROOT, 'lib', 'disharmony')

# mirrored new shows
Disharmony::Show.all(:limit => 5, :order => [:air_date.desc], :conditions => {:mirrored => false}).each do |s|
  puts "uploading show #{s.mp3}"
  mirror = Disharmony::Mirror.new(s)
  mirror.post!
end
