#!/usr/bin/env ruby

ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
ENV['RACK_ENV'] = 'production'

require "rubygems"
require "bundler"
Bundler.setup

require File.join(ROOT, 'lib', 'disharmony')

Disharmony::Logger = Logger.new(STDOUT)

# downloads all new shows released in the current month
Disharmony.new.download_recent
