#!/usr/bin/env ruby

ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
ENV['RACK_ENV'] = 'production'

require 'rubygems'
require 'ruby-debug'

require 'bundler'
Bundler.setup

Dir[File.join(ROOT, "vendor/*/lib")].each { |path| $:.unshift path } 

require File.join(ROOT, 'lib', 'disharmony')

Disharmony::Logger = Logger.new(STDOUT)

date = Date.new(2007,1)

Disharmony.new.download_for_date(date)
